# Generated by Django 4.1.3 on 2022-11-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='updated',
        ),
    ]
