# Generated by Django 4.1.3 on 2022-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_rename_carrer_about_carreer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='up_dated',
        ),
        migrations.RemoveField(
            model_name='home',
            name='up_dated',
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=50),
        ),
    ]
