# Generated by Django 4.1.3 on 2022-12-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_about_up_dated_remove_home_up_dated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='created',
        ),
        migrations.RemoveField(
            model_name='home',
            name='created',
        ),
    ]
