# Generated by Django 4.1.3 on 2022-12-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_about_created_remove_home_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='education',
            name='created',
        ),
        migrations.RemoveField(
            model_name='education',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='language',
            name='created',
        ),
        migrations.RemoveField(
            model_name='language',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
    ]
