# Generated by Django 4.1.3 on 2022-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_created_about_updated_category_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
