# Generated by Django 4.1.3 on 2022-12-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_language_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created'], 'verbose_name': 'Sobre', 'verbose_name_plural': 'Sobre-me'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created'], 'verbose_name': 'Certifición', 'verbose_name_plural': 'Certificiones'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-created'], 'verbose_name': 'Hogar', 'verbose_name_plural': 'Hogares'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-created'], 'verbose_name': 'Lenguaje', 'verbose_name_plural': 'Lenguajes'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolios'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': ' Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
